### ISSUE TITLE
[epic] Enhance Prompt Script view to "calculate" with a list of chunks

### ISSUE THREAD

**Issue by triathematician** [aplpolaris/promptfx#123]
- [x] Add additional features to the Prompt Script tool view:
  - [x] #134
  - [x] #124
  - [x] #125
  - [x] #126
  - [x] #127
  - [x] #128
  - [x] #129
- [x] Update views for `TextChunk`
  - [x] #132
  - [x] #133
  - [x] Related: #122
- [x] Update views for `PromptTrace`
  - [x] #137
  - [x] #140
  - [x] #141
  - [x] #143
- [x] General UI cleanup
  - [x] #135
  - [x] #139
  - [x] #142
