### ISSUE TITLE
[epic] TextLibrary wizard for document chunking and embedding calculations

### ISSUE THREAD

**Issue by triathematician** [aplpolaris/promptfx#144]
The view should be able to:

- [x] View
  - [x] #145
  - [x] #168
  - [x] TextDataManager view does not shown the "run" button
  - [x] #169
- [x] Chunking support
  - [x] #147
  - [x] #148
  - [x] #149
  - [x] #150
  - [x] #151
  - [x] #161
- [x] Embedding support
  - [x] #152
  - [x] #153
  - [x] #154
  - [x] #155
- [x] Improvements to promptkt chunking system
  - [x] #156
  - [x] #157
  - [x] #158 
- [x] Refactoring old chunking system
  - [x] #122
  - [x] #171
- [x] Improvements to UI
  - [x] #167

Related Issues (to be completed later):
- #34
- #146

Testing
- [x] The embeddings file is reloaded automatically when you run promptfx again
- [x] The auto-calculated embeddings file can be loaded in the text library view
- [x] Can import a legacy embeddings file without recalculating everything
- [x] Can save and restore multiple embedding models
- [x] Can move `embeddings2.json` and files to a new folder, and it will automatically swap out paths
- [x] Command-line tool for chunking works, can load result in library view
- [x] Command-line tool for embedding works, can load result in library view
