### ISSUE TITLE
[feat] UI option to extract metadata from multiple pages of document text

### ISSUE THREAD

**Issue by triathematician** [aplpolaris/promptfx#267]
Analytics:
- [x] Guess title and authors of document
- [x] Guess sections of document, with detailed text for abstracts and executive summaries
- [x] Guess references
- [x] Guess other parts of documents

User interface:
- [x] UI context menu to open metadata viewer/validator
- [x] #270
  - [x] Option to pull metadata from file
  - [x] Option to "guess" metadata from user-specified number of pages
- [x] #271
  - [x] Shows currently saved metadata (loads by default)
  - [x] Shows whether metadata is saved or not saved (with the document as represented in the viewer)
  - [x] If more than one option are available for a given metadata key, allows users to cycle through alternates
  - [x] Users can "Save" displayed metadata to update the document metadata
  - [x] Alternate icon than a save disk, since the "save" is only temporary
  - [x] Users can remove metadata from displayed list
- [x] "Save" or "Apply Changes" button in button bar, applying selected metadata updates to the document (confirm with user on save)
- [x] "Cancel" or "Close" button in button bar, to negate any user changes

Other improvements:
- [ ] Text manager view provides folder/open links to collection file (already in context menu, could be future feature)
