### ISSUE TITLE
[epic] Create a scatterplot UI using dimensional reduction to visualize text chunks and clusters

### ISSUE THREAD

**Issue by triathematician** [aplpolaris/promptfx#313]
- [ ] Scatterplot UI
  - [ ] [feat] Create an interface for performing dimensional reductions on embeddings
  - [ ] [feat] Create a scatterplot view of selected text chunks that can be colored by clusters
  - [ ] [feat] In scatterplot view, enable users to search and highlight found chunks
